### ISSUE TITLE
Implement getSpriteCount

### ISSUE THREAD

**Issue by fenwickjb** [JaysGitLab/cs-5666-scatt-brandy#4]
With sb2 file unzipped, now we can begin consulting the contents to learn various attributes such as the number of sprites.
int getSpritecount()

**Comment by matts-dev** [comment]
Hey guys, I'll have to get my unzipper fixed before we can start this. I just wanted to show Broderick how we assigned ourselves to issues. I went ahead and assigned you to this one, but that was mostly just to show you that is how we claim what we're working on. Normally, we pick what ever want to work on and assign ourselves to those issues. You guys can de-assign yourself if you don't want to work on this. :P
